# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': '\u041d\u0430\u0437\u0432\u0430 \u0442\u043e\u0432\u0430\u0440\u0443', 'verbose_name_plural': '\u041d\u0430\u0437\u0432\u0438 \u0442\u043e\u0432\u0430\u0440\u0456\u0432'},
        ),
    ]
